---
- name: Include OS family-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure EPEL repo is installed
  yum:
    name: epel-release
    state: installed
  become: True
  when:
    - ansible_os_family == 'RedHat'
    - os_openstackclient_install_epel | bool

- name: Ensure required packages are installed
  package:
    name: "{{ item }}"
    state: installed
  become: True
  with_items: "{{ os_openstackclient_package_dependencies }}"
  when: os_openstackclient_install_package_dependencies | bool

- name: Check whether the virtualenv directory exists
  stat:
    path: "{{ os_openstackclient_venv | dirname }}"
    get_md5: False
    get_checksum: False
    mime: False
  when: os_openstackclient_venv != None
  register: os_openstackclient_venv_stat

- name: Ensure the virtualenv directory exists
  file:
    path: "{{ os_openstackclient_venv | dirname }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: True
  when:
    - os_openstackclient_venv != None
    - not os_openstackclient_venv_stat.stat.exists

- name: Ensure the latest version of pip is installed
  pip:
    name: "{{ item.name }}"
    state: latest
    virtualenv: "{{ os_openstackclient_venv or omit }}"
  with_items:
    - { name: pip }

- name: Ensure required Python packages are installed
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version or omit }}"
    state: present
    virtualenv: "{{ os_openstackclient_venv or omit }}"
  with_items:
    - name: python-openstackclient
      version: "{{ os_openstackclient_version }}"
